### ISSUE TITLE
Custom thumbnail flashes and displays the original video thumbnail

### ISSUE THREAD

**Issue by canastro** [newtaDev/pod_player#58] opened 2022-08-04 09:49 UTC
When I add a custom `thumbnail` I expect that thumbnail to be the one rendered up-until the user presses play. Yet, it seems that once the PodPlayer loads the video thumbnail it tries to display it creating a flash of different thumbnails.

https://user-images.githubusercontent.com/1267623/182817451-98fb48fe-d3f7-4b4b-8ea7-46b449295f03.mov

A snippet of the code:

```dart
late final controller = PodPlayerController(
    playVideoFrom: PlayVideoFrom.vimeo(widget.resource.url),
    podPlayerConfig: const PodPlayerConfig(autoPlay: false),
);

PodVideoPlayer(
    controller: controller,
    videoThumbnail: DecorationImage(
        image: CachedNetworkImageProvider(widget.resource.thumbnailURL),
        fit: BoxFit.cover,
    ),
),
```

**Comment by newtaDev** [comment] 2022-08-05 06:31
Thank you for filling the issue 🤗
ref: https://github.com/newtaDev/pod_player/issues/52#issuecomment-1198876772
Please continue your discussion here #52
I'm closing this issue because this issue is duplicate of #52

**Closed by newtaDev** 2022-08-05 06:31 UTC
Labels: bug, duplicate
