### ISSUE TITLE
 VIMEO API ERROR: NoSuchMethodError: The getter 'length' was called on null.

### ISSUE THREAD

**Issue by chatali96** [newtaDev/pod_player#183] opened 2024-04-10 06:29 UTC

**Comment by greatschism** [comment] 2024-04-10 09:36
It is because they removed the key **progressive** from the API. I emailed Vimeo, and they haven't been helpful.

**Comment by newtaDev** [comment] 2024-04-10 15:20
> It is because they removed the key **progressive** from the API. I emailed Vimeo, and they haven't been helpful.

Yeah, They have changed their API response,
Let me see if I can find a fix for this issue ASAP

**Comment by harrydebut** [comment] 2024-04-10 16:03
our client app videos are stuck due to this viemo issue. Is it possible to fix this by today EOD or latest by tomorrow? Do you have any recommendations for another video player that can work with it? cauz , client app is having 4000 paid users and client is very furious on us

**Comment by newtaDev** [comment] 2024-04-10 16:19
> our client app videos are stuck due to this viemo issue. Is it possible to fix this by today EOD or latest by tomorrow? Do you have any recommendations for another video player that can work with it? cauz , client app is having 4000 paid users and client is very furious on us

Sorry to hear,
But I will try to deploy the fix today itself

**Comment by newtaDev** [comment] 2024-04-10 16:22
Im closing this issue, because it is a dupe of #182 
we can continue the conversation here #182

**Closed by newtaDev** 2024-04-10 16:22 UTC
